# Generated by Django 4.0.4 on 2023-03-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0002_apartment_permalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='baths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
